### ISSUE TITLE
Copy ssl-dh-param-file

### ISSUE THREAD

**Issue by mvdriel** [Oefenweb/ansible-haproxy#126]
Thank you for this nice and complete role!

To replicate the configuration suggested by the Mozilla SSL Configuration Generator (https://ssl-config.mozilla.org/#server=haproxy&version=1.8.8&config=intermediate&openssl=1.1.1&guideline=5.6) I'm looking for a way to copy a ssl-dh-param-file. @tersmitten Do you have any suggestion how I can do this in this role?

**Comment by tersmitten** [comment]
I not sure if there's one now. I'll have a look.

We include them in the (combined) `pem` files (so a custom `dhparams.pem` per certificate). Something like this:

```sh
# cat files/haproxy/staging-app/etc/haproxy/ssl/star-app-staging-oefenweb-nl/README.txt 
if [ ! -f dhparams.pem ]; then
  openssl dhparam -out dhparams.pem 2048;
fi

...

# adds \n at the end of the file only if it doesn't already end with a newline
sed -i -e '$a\' certificate.crt;

cat certificate.crt certificate.key cabundle.crt dhparams.pem > certificate.pem;

# remove empty lines
sed -i -e '/^\s*$/d' certificate.pem;

openssl verify -CAfile cabundle.crt certificate.pem;

# cleanup
rm ./cabundle-certificate-*.crt;
```

**Comment by tersmitten** [comment]
You can probably use `haproxy_ssl_map`. That should allow for any upload, it even creates target directories :-)

**Comment by mvdriel** [comment]
@tersmitten Thanks! `haproxy_ssl_map` works like a charm.
