### ISSUE TITLE
Adding options to global section

### ISSUE THREAD

**Issue by ojan** [Oefenweb/ansible-haproxy#38]
adding this snippet in  `templates/etc/haproxy/global.cfg.j2`

~~~~
{% for option in haproxy_global_options | default([]) %}
  {{ option.key }} {{ option.value }}
{% endfor %}
~~~~

gives the opportunity to load some lua modules or anything else in HAProxy

~~~
haproxy_global_options:
   - key: lua-load
     value: /etc/haproxy/acme-http01-webroot.lua
~~~

Maybe this is a duplicate possibility of something i didn't find. If not, tell me if it worse a pull request :-)

**Comment by tersmitten** [comment]
This would be a welcome addition! 

Can you make it like `haproxy_defaults_option`? Just to be consistent :-)

**Comment by ojan** [comment]
Just to be sure before proposing the consistent pull request :-)

Added `haproxy_global_option: []` in `defaults/main.yml`

Added in `templates/etc/haproxy/global.cfg.j2`

~~~
{% if haproxy_global_option != false %}
{% for option in haproxy_global_option %}
  {{ option }}
{% endfor %}
{% endif %}
~~~

This gives you the possibility to add in a playbook vars for example:

~~~
haproxy_global_option:
   - lua-load /etc/haproxy/acme-http01-webroot.lua
   - ssl-dh-param-file /etc/haproxy/dhparams.pem
   - spread-checks 4
~~~

**Comment by tersmitten** [comment]
Looks good
