### ISSUE TITLE
Can't add logging option to listen section

### ISSUE THREAD

**Issue by GhostPunk** [Oefenweb/ansible-haproxy#40]
I'd like to use the following option in the listen section:
https://cbonte.github.io/haproxy-dconv/configuration-1.7.html#4.2-no%20log

However at the time this is not possible if I'm not mistaken. I would be happy to make a pull request to fix this just thinking about how to handle. Would it be better like the solution in #38 and move towards a general approach or just extend haproxy_listen.{n} and add "log"?

I think it applies to backend and frontend too.

**Comment by tersmitten** [comment]
The last one please:
> extend haproxy_listen.{n} and add "log"

Can you also make sure to add documentation?

Thanks in advance for adding this feature.
