### ISSUE TITLE
haproxy_global_log.format should be haproxy_default_log.format

### ISSUE THREAD

**Issue by ojan** [Oefenweb/ansible-haproxy#51]
Hi,

Correct me if i'm wrong but i think haproxy_global_log.format should be haproxy_default_log.format cause haproxy configuration doesn't validate if `log_format` directive put in `global section`, at least with version 1.7. If correct, global and default template need slight modification and variable must be renamed.

**Comment by tersmitten** [comment]
What about http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#log?

**Comment by ojan** [comment]
I know about that link, one of my favourite reading ;-)

Let's make a try

```
global
  log /dev/log local0
  log-format {\"hostname\":\"%H\",\"…}
```
gives a `unknown keyword 'log-format' in 'global' section`. One of my friend has the same result with haproxy 1.6.x

**Comment by adrianmoisey** [comment]
I've just come across this bug too. log-format isn't a global option.

**Comment by tersmitten** [comment]
Can you guys prepare a pull request?

**Comment by adrianmoisey** [comment]
I’ll do it

**Comment by tersmitten** [comment]
Thanks
