### ISSUE TITLE
log length option

### ISSUE THREAD

**Issue by ojan** [Oefenweb/ansible-haproxy#55]
Me again,

I could not find a `haproxy_global_log.{n}.length` option so added one with this snippet in `templates/etc/haproxy/global.cfg.j2`

```
log {{ log.address }}{% if log.length is defined %} len {{log.length }}{% endif %} {{ log.facility }}{% if log.level is defined %} {{log.level }}{% endif %}…
```

**Comment by tersmitten** [comment]
No worries, thanks for all your contributions

**Comment by tersmitten** [comment]
Can you make a pull request?

**Comment by ojan** [comment]
done
