### ISSUE TITLE
Issue inserting cookie

### ISSUE THREAD

**Issue by alejandroed** [Oefenweb/ansible-haproxy#83]
Hi!

I´m trying to insert a cookie in my backend with;
cookie:
      - SERVERID insert indirect nocache

But it translates into the cfg with this line:

cookie [u'SERVERID insert indirect nocache']

instead cookie SERVERID insert indirect nocache

any ideas?

**Comment by tersmitten** [comment]
As far as I can see there's only support in add 1 cookie, [see](https://github.com/Oefenweb/ansible-haproxy/blob/master/templates/etc/haproxy/backend.cfg.j2#L31). Try changing:
```yaml
cookie:
  - SERVERID insert indirect nocache
```
to
```yaml
cookie: SERVERID insert indirect nocache
```

**Comment by alejandroed** [comment]
It works! thank you!
