### ISSUE TITLE
PPA / Ubuntu dependency

### ISSUE THREAD

**Issue by gandhiano** [Oefenweb/ansible-haproxy#84]
While attempting to use this role on a debian system, I came across a single failure, which is related to the addition of the ppa repository (on `install.yml`). Running a playbook with `--skip-tags haproxy-install-add-repository` I managed to successfully deploy the role on a debian system.

Unless there are strong reasons to keep it like that and force the use of an ubuntu-specific PPA, I would suggest removing this strong dependency or making it conditional, based on installed system or variable definition.

**Comment by tersmitten** [comment]
The PPA is needed to be able to install multiple / newer versions that are not included in the OS

See:
* https://haproxy.debian.net/#?distribution=Ubuntu&release=xenial&version=1.8
* https://haproxy.debian.net/#?distribution=Debian&release=stretch&version=1.8

**Comment by gandhiano** [comment]
Then maybe we can make a conditional check to allow also debian hosts to use this, even if with limited version options? 

I would be happy to attempt providing a pull request for this in the next weeks if you feel interesting to extend this role.

Am 21. Dezember 2018 15:53:21 MEZ schrieb Mischa ter Smitten <notifications@github.com>:
>The PPA is needed to be able to install multiple / newer versions that
>are not included in the OS
>
>See:
>*
>https://haproxy.debian.net/#?distribution=Ubuntu&release=xenial&version=1.8
>*
>https://haproxy.debian.net/#?distribution=Debian&release=stretch&version=1.8
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Oefenweb/ansible-haproxy/issues/84#issuecomment-449408536

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tersmitten** [comment]
Feel free to open a PR, I'm interested

**Comment by aaronwmorris** [comment]
I have submitted PR #98 to support multiple distributions.  This PR only adds Debian, but additional repos should be relatively easy to add.

**Comment by tersmitten** [comment]
Using `haproxy_use_ppa` might work for you
