### ISSUE TITLE
Support for reqrep

### ISSUE THREAD

**Issue by chmduquesne** [Oefenweb/ansible-haproxy#85]
Hi,

I would like to use [reqrep](https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#4-reqrep) in an ansible_backend context. Is it possible to add support for this?

(The directive may appear several times)

I can do a PR if needed.

Cheers,
Christophe-Marie

**Comment by tersmitten** [comment]
Feel free to make a PR, I think it's a nice addition
